#! /bin/bash

for filename in $(git diff --cached --name-only | grep '.*\.[c|h]$'); do
  clang-format -style=file -i $filename; git add $filename;
done

for filename in $(git diff --cached --name-only | grep '.*\.go$'); do
  gofmt -s -w $filename; git add $filename;
done

for filename in $(git diff --cached --name-only | grep '.*\.jsonc$'); do
  ./tools/check_json.py --schema ./tools/cndp.schema $filename
done
