#! /bin/bash

for filename in $(git diff --cached --name-only | grep '.*\.[c|h]$'); do
  if [ -f "$filename" ]; then
    clang-format -style=file -i "$filename"; git add "$filename";
  fi
done

for filename in $(git diff --cached --name-only | grep '.*\.go$'); do
  if [ -f "$filename" ]; then
    gofmt -s -w "$filename"; git add "$filename";
  fi
done

for filename in $(git diff --cached --name-only | grep '.*\.jsonc$'); do
  if [ -f "$filename" ]; then
    ./tools/check_json.py --schema ./tools/cndp.schema "$filename"
  fi
done
