# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.4
    hooks:
      - id: clang-format
        types_or: [c++, c]
        args: [-i, --style=file]
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.0
    hooks:
      - id: markdownlint-cli2-rules-docker
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [--toml, cndp-codespell.precommit-toml]
        additional_dependencies:
          - tomli
exclude: doc/api/doxy-api-index.md|lang/rs/wireguard/patch/000*.*

ci:
  autofix_commit_msg: |
      [pre-commit.ci] auto fixes from pre-commit.com hooks

      for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: [markdownlint-cli2-rules-docker]
  submodules: false
