#!/bin/bash

cdir=$(pwd)
PROJECT_PATH="${cdir}/../../../../.."

cmdstring="sudo -E LD_LIBRARY_PATH=$PROJECT_PATH/usr/local/lib/x86_64-linux-gnu \
    LD_PRELOAD=$PROJECT_PATH/usr/local/lib/x86_64-linux-gnu/libpmd_af_xdp.so ./fwd $*"

go mod tidy
rc=$?
if [[ $rc -ne 0 ]]; then
    echo "Go tidy failed"
    exit $rc
fi

go build
rc=$?
if [[ $rc -ne 0 ]]; then
    echo "Go build failed"
    exit $rc
fi

$cmdstring

stty sane
