# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Intel Corporation

common_pkgs:
  ubuntu:
    - build-essential
    - libbsd-dev
    - libelf-dev
    - libjson-c-dev
    - libnuma-dev
    - libpcap-dev
    - meson
    - pkg-config
    - doxygen
    - python3-sphinx
    - libnl-3-dev
    - libnl-cli-3-dev
  fedora:
    - "@development-tools"
    - git
    - libbsd-devel
    - json-c-devel
    - libnl3-devel
    - libnl3-cli
    - numactl-libs
    - meson
    - ninja-build
    - gcc-c++
    - libpcap
    - libpcap-devel
