# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2020-2025 Intel Corporation.

[package]
name = "fwd"
version = "0.1.0"
edition = "2021"

[dependencies]
# cndp-cne package is in cndp repo.
# Cargo will crawl the entire cndp repo looking for cndp-cne package.
cndp-cne = {git = "https://github.com/CloudNativeDataPlane/cndp", branch = "main" }
crossbeam-channel = "0.5.15"
clap = { version = "3.2.25", features = ["derive"] }
ctrlc = "3.5.0"
etherparse = "0.10.1"
env_logger = "0.9.3"
hex = "0.4"
log = "0.4"
prettytable-rs = "0.10.0"
term = "0.7"
