# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2020-2023 Intel Corporation
---
- hosts: localhost
  vars:
    localhost_install: true
    become: true
    become_user: root
  tasks:
    - include_role:
        name: gen_config
        apply:
          delegate_to: localhost
      tags: 00_gen_config
    - include_role:
        name: config_ethtool
        apply:
          delegate_to: localhost
      tags: 00_config_ethtool
