#!/bin/bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Intel Corporation

cdir=$(pwd)
PROJECT_PATH="${cdir}/../../../../.."

cmdstring="sudo -E LD_LIBRARY_PATH=$PROJECT_PATH/usr/local/lib/x86_64-linux-gnu ./sampling $*"
go env -w CGO_LDFLAGS_ALLOW='-Wl,--(?:no-)?whole-archive'

go mod tidy
rc=$?
if [[ $rc -ne 0 ]]; then
    echo "Go tidy failed"
    exit $rc
fi

go build
rc=$?
if [[ $rc -ne 0 ]]; then
    echo "Go build failed"
    exit $rc
fi

$cmdstring

stty sane
