# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2020-2023 Intel Corporation
---
# This role checks how much memory is available on the system for
# hugepage allocation
- name: Memory Check
  fail:
    msg:
      - trying to allocate {{ ((hugepages_2MB|int * 2) + (hugepages_1GB|int * 1024)) }} MiB of
      - memory only {{ ansible_memtotal_mb }} MiB available
  when: ansible_memtotal_mb < ((hugepages_2MB|int * 2) + (hugepages_1GB|int * 1024))
  tags:
    - check_mem

- name: Memory Check Success
  debug:
    msg: Memory Check is good
  tags:
    - check_mem
