#!/bin/bash

cdir=$(pwd)
PROJECT_PATH="${cdir}/../../../.."

precmd="sudo -E LD_LIBRARY_PATH=$PROJECT_PATH/usr/local/lib/x86_64-linux-gnu"
cmdstring="$precmd ./cne.test -test.v -config ../examples/fwd/fwd.jsonc"

go env -w CGO_LDFLAGS_ALLOW='-Wl,--(?:no-)?whole-archive'

function go_tidy() {
    go mod tidy
    rc=$?
    if [[ $rc -ne 0 ]]; then
        echo "Go tidy failed"
        exit $rc
    fi
}

function go_test() {
    go test -c
    rc=$?
    if [[ $rc -ne 0 ]]; then
        echo "Go test failed"
        exit $rc
    fi
}

rm -f cne.test
(go_tidy && go_test && $cmdstring)

rm -f cne.test
stty sane
