# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2020-2022 Intel Corporation

---
# This role installs all the packages needed for CNDP
# Template for installing packages
#- name: install
#  package:
#     name:
#     state: present
#  environment: "{{ proxy_env }}"
#  tags: install_pkgs

- name: update package manager cache
  tags:
     - cache_update
  package:
     update_cache: yes
  environment: "{{ proxy_env }}"

- name: install build-essential
  package:
     name: build-essential
     state: present
  environment: "{{ proxy_env }}"
  tags: install_pkgs

- name: install libbsd-dev
  package:
     name: libbsd-dev
     state: present
  environment: "{{ proxy_env }}"
  tags: install_pkgs

- name: install libelf-dev
  package:
     name: libelf-dev
     state: present
  environment: "{{ proxy_env }}"
  tags: install_pkgs

- name: install libjson-c-dev
  package:
     name: libjson-c-dev
     state: present
  environment: "{{ proxy_env }}"
  tags: install_pkgs

- name: install libnuma-dev
  package:
     name: libnuma-dev
     state: present
  environment: "{{ proxy_env }}"
  tags: install_pkgs

- name: install libpcap-dev
  package:
     name: libpcap-dev
     state: present
  environment: "{{ proxy_env }}"
  tags: install_pkgs

- name: install meson
  package:
     name: meson
     state: present
  environment: "{{ proxy_env }}"
  tags: install_pkgs

- name: install pkg-config
  package:
     name: pkg-config
     state: present
  environment: "{{ proxy_env }}"
  tags: install_pkgs

- name: install doxygen
  package:
     name: doxygen
     state: present
  environment: "{{ proxy_env }}"
  tags: install_pkgs

- name: install python3-sphinx
  package:
     name: python3-sphinx
     state: present
  environment: "{{ proxy_env }}"
  tags: install_pkgs

- name: install libnl-3-dev
  package:
     name: libnl-3-dev
     state: present
  environment: "{{ proxy_env }}"
  tags: install_pkgs

- name: install libnl-cli-3-dev
  package:
     name: libnl-cli-3-dev
     state: present
  environment: "{{ proxy_env }}"
  tags: install_pkgs

