# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2020-2023 Intel Corporation

---
# This role checks if the right base OS is installed for
# CNDP
- name: Distribution Check
  fail:
    msg: CNDP requires {{ required_dist }} {{ dist_ver }}
  when: (ansible_distribution != required_dist) or
        (ansible_distribution_version is version (dist_ver, '<'))
  tags:
    - check_os

- name: Distribution Check
  debug:
    msg: Distribution is good
  tags:
    - check_os
