# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2020-2022 Intel Corporation.

[package]
name = "cndp-cne"
description = "Cloud Native Data Plane (CNDP) Rust API"
repository = "https://github.com/CloudNativeDataPlane/cndp"
homepage = "https://cndp.io/"
readme = "README.md"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"
keywords = ["networking", "cloud native", "AF_XDP"]

[lib]
name = "cne"

[dependencies]
cndp-cne-sys = { path = "../../bindings/cne-sys" }
once_cell = "^1.10"
indexmap = { version = "^1.8", features = ["serde-1"] }
json_comments = "^0.2"
nix = "^0.24"
num_cpus = "^1.0"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
spin = "^0.9"

[dev-dependencies]
etherparse = "^0.10"
env_logger = "^0.8"
hex = "^0.4"
log = "0.4"
