name: clang-format

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: DoozyX/clang-format-lint-action@v0.17
        with:
          source: '.'
          exclude: 'examples/vpp-plugin'
          extensions: 'h,cpp,c,cc'
          clangFormatVersion: 17
