name: Docker Image Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Docker:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    # Set an output parameter `arch` for use in subsequent steps
    - name: Get processor architecture
      id: system
      run: |
        echo ::set-output name=arch::$(uname -m)

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Create tags and labels
      id: image_meta
      uses: docker/metadata-action@v3
      with:
        sep-tags: ","
        sep-labels: ","
        # list of names to use as base name for tags
        images: |
          ghcr.io/${{ github.repository_owner }}/cndp-ubuntu-${{ steps.system.outputs.arch }}
        # Docker tags based on the following events/attributes
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha

    - name: Build Ubuntu Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: "${{ steps.image_meta.outputs.tags }}"
        file: containerization/docker/ubuntu/Dockerfile

    - name: Build Fedora Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: "${{ steps.image_meta.outputs.tags }}"
        file: containerization/docker/fedora/Dockerfile
