name: Docker Image Build

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - .github/workflows/docker.yml
      - containerization/docker/fedora/Dockerfile
      - containerization/docker/ubuntu/Dockerfile
      - containerization/docker/ubuntu/fwd.jsonc
  pull_request:
    paths:
      - .github/workflows/docker.yml
      - containerization/docker/fedora/Dockerfile
      - containerization/docker/ubuntu/Dockerfile
      - containerization/docker/ubuntu/fwd.jsonc
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: make oci-image
