name: Pre-commit auto-update
on: # yamllint disable-line rule:truthy
  schedule:
    - cron: 0 0 1 * *

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit auto update
        run: pre-commit auto update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: pre-commit-auto-update
          title: Auto-update pre-commit hooks
          commit-message: Auto-update pre-commit hooks
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          sign-commits: true
          body: |
            Update pre-commit hooks to latest version
          draft: false
