name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  PKG_CONFIG_PATH: "$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig"
  LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:/usr/local/lib/x86_64-linux-gnu"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Install packages
      run: |
        sudo apt-get update && sudo apt-get install -y\
          build-essential libbsd-dev libelf-dev libjson-c-dev\
          libnl-3-dev libnl-cli-3-dev libnuma-dev libpcap-dev meson\
          pkg-config wget libbpf-dev llvm-dev libclang-dev clang

    # - name: Install Rust
    #   run: |
    #       curl https://sh.rustup.rs -sSf | sh -s -- -y
    #       source "$HOME/.cargo/env"

    - name: Build and Install CNDP
      run: make; make install

    - name: Build
      working-directory: lang/rs
      run: CNDP_INSTALL_PATH=${{ github.workspace }} cargo build
