# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2020-2022 Intel Corporation.

[package]
name = "loopback"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
cndp-cne = { path = "../.." }
core_affinity = "0.5.10"
crossbeam-channel = "0.5.4"
clap = "3.2.11"
ctrlc = "3.2.2"
etherparse = "0.10.1"
env_logger = "0.9.0"
log = "0.4"
